version: "3.0"
services:
  db:
    container_name: "db"
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    networks:
      - custom
    volumes:
      - postgres-data:/var/lib/postgresql/data/
  app:
    container_name: app
    image: app
    depends_on:
      - db
      - alembic_migrations
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - DATABASE_HOST=db
      - APP_PORT=8000
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - custom
  alembic_migrations:
    container_name: alembic_migrations
    image: alembic_migrations
    command: ./run.sh
    depends_on:
      - db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - DATABASE_HOST=db
      - APP_PORT=8001
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    networks:
      - custom
networks:
  custom:
    driver: bridge
volumes:
  postgres-data:
